[package]
name = "pinocchio_fundraiser"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pinocchio = "0.9.2"
pinocchio-system = "0.3.0"
pinocchio-token = "0.4.0"
pinocchio-pubkey = { git = "https://github.com/anza-xyz/pinocchio.git" }
pinocchio-log = "0.5.1"
pinocchio-associated-token-account = "0.2.0"
bytemuck = { version = "1.23.0", features = ["derive"] }
shank = "0.4.2"
solana-program = "3.0.0"

[dev-dependencies]
litesvm = "0.8.1"
solana-sdk = "2.2.1"


[features]
no-entrypoint = []
std = []
test-default = ["no-entrypoint", "std"]
